#!/bin/sh
#  $Id: pack,v 1.3 2006-01-30 10:21:43 gap Exp $
if let "$# != 2"; then
  echo "Usage: pack dir version  (like:  pack edim 1.2)"
  echo "(produces a dir-version.tar.bz2  file)"
  exit
fi


find $1 -regex ".*\(/CVS\|CVS/.*\|~\|/pack\|\.aux\|\.log\|/index.html\|/bla.xml\)" | tar cv $1 --exclude-from - |bzip2 -c -9 > $1-$2.tar.bz2

